Metaverso9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import inicio


urlpatterns = [
    path("admin/", admin.site.urls),
    path("inicio/", inicio, name='inicio'),
    path("Noticias/", include('apps.noticias.urls')),
    path("opiniones/", include('apps.opiniones.urls')),
    path('usuarios/', include('apps.usuarios.urls', namespace='usuarios')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name = 'usuarios'

urlpatterns = [
path('registrar/',views.RegistrarUsuario.as_view(), name='registrar'),
    path('iniciar_sesion/', LoginView.as_view(template_name="usuarios/iniciar_sesion.html"), name='iniciar_sesion'),
    path('cerrar_sesion/', LogoutView.as_view(), name='cerrar_sesion'),
    path('listar_usuarios/', ListarUsuarios, name='listar_usuarios'),
    path("eliminar_usuario/<int:pk>", EliminarUsuario.as_view(), name='eliminar_usuario'),
       

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}
    {% endblock %}
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body class="body">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@100&display=swap" rel="stylesheet">
    <div>
        {% block navegacion %}
        {% endblock %}
    </div>
    <div>
        {% block contenido %}
        {% endblock %}
    </div>
    <!-- Footer -->

    <footer>
        <div style="margin-top: 5%;" class="card-footer text-body-secondary text-center">
            <h3>Comisión 4 Grupo 9 </h3>
        </div>
    </footer>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
<title>Inicio</title>
{% endblock %}
{% block navegacion %}
{% include 'navegacion.html' %}
{% endblock %}
{% block contenido %}
<div class="card text-bg-dark">
    <img class="card-img" src="{% static 'img/fondo3.jpg' %}" alt="libreria">
    <div class="card-img-overlay">
        <h3
            style="color: rgb(228, 227, 227); text-align: center; font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
            Bienvenidos a la pagina de noticias METAVERSO9!
            Vas a encontrar todas las noticias relacionadas con el tema, sus opiniones y también dejar tu opinion respecto a
            esto!
            Registrate y sumate a la comunidad!
        </h3>
    </div>
</div>
<section class="my-5">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100 rounded" src="{% static 'img/img_libros/Noticia1.jpeg' %}" alt="Noticia 1">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 rounded" src="{% static 'img/img_libros/Noticia2.jpg' %}" alt="Noticia 2">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 rounded" src="{% static 'img/img_libros/Noticia3.jpg' %}" alt="Noticia 3">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Anterior</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Siguiente</span>
            </button>
        </div>
    </div>
</section>
{% endblock %}

templates/navegacion.html
{% load static %}
<nav class="navbar" data-bs-theme="dark">
    <div class="container-fluid">
        <a href="{% url 'inicio' %}">
            
        </a>

        <ul class="nav nav-underline">
            {% if user.is_authenticated %}
            <div class="list-group-item d-flex gap-3 py-3" aria-current="true">
                <img src="{{ user.imagen.url }}" alt="perfil" width="40" height="40"
                    class="rounded-circle flex-shrink-0">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{user.username}}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="">Modificar
                                    Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:cerrar_sesion' %}">Cerrar sesión</li></a>
                        </ul>
                    </li>
                </ul>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:registrar' %}">Registrarse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usuarios:iniciar_sesion' %}">Iniciar Sesión</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'apps.noticias:listar_libros' %}">Noticias</a>
                </li>
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Noticias
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'apps.noticias:listar_libros' %}">Todos</a></li>
                        {% for i in categorias %}
                        <li><a class="dropdown-item"
                                href="{% url 'apps.noticias:listar_por_categoria' i.nombre %}"></a>>>{{i.nombre}}
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if user.es_colaborador %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Administrador
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'apps.noticias:agregar_categoria' %}">Agregar
                                categoria</a></li>
                        <li><a class="dropdown-item" href="{% url 'apps.noticias:agregar_libro' %}">Agregar
                                Noticia</a></li>
                        <li><a class="dropdown-item" href="{% url 'apps.usuarios:listar_usuarios' %}">Listar
                                usuarios</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

</nav>